FactoryGirl.define do
  factory :bhsi_longtext do
    about_yourself                        "Mark Kabban is changing the lives of child survivors of war in San Diego - but you'll never hear this from him. Swift to always give others credit before taking it himself, Mark's humble and brilliant leadership is transforming a community by increasing access to healthy recreation and connecting families to much needed resources. In just 3 years, YALLA has quickly become a nationally recognized and model program due to Mark's ability to strategically invest limited resources to advance innovative solutions towards ensuring that marginalized children have a shot at a prosperous and healthy future.\r\nMark's tireless efforts have played a vital role in strengthening our region's capacity to help refugee and immigrant families acclimate to their new communities, schools, and environments. To date, he has increased access to soccer programs for nearly  600 children who might not otherwise have healthy, active recreation.  He has provided over 250 children with afterschool educational programs, professional development and created opportunities for children to access nature, which research shows helps us heal from the traumas of war. \r\n2011 Do Something Award Finalist\r\n2012 CNN Hero Award"
    social_venture_description            "With college as the goal, YALLA is the first and only program in California that uses soccer as a hook to engage refugee and immigrant youth in education and eco-therapy programs."
    venture_launched                      "2010"
    number_people_affected                "Over 600"
    explain_number                        "600 child survivors of war, refugee/immigrant and other marganilized youth have received one or all 4 of YALLA's programs"
    organizational_development            "To date YALLA has two full time employees and also has two part time education directors, a volunteer coordinator, a community program manager, eco-therapy director, soccer director and a grant writer. YALLA also awards stipends to fifteen older refugee youth as coaches and referees as part of the mentorship program. A board of directors composed of nonprofit professionals, professors, medical doctors, evaluators and refugee experts.. In addition, YALLA has established relationships with local universities to receive reliable interns throughout the year. YALLA's funding comes from individual donors, the San Diego Foundation for Change, US Youth Soccer, UPS and the biggest being the LA 84 foundation. YALLA's annual budget is $107,000. "
    strong_midwest_connections_explained  "I graduated from Baker University in Kansas. I have professors from my university that still write grants and edit YALLA\"s literature. I graduated from Baker University in Kansas. I have professors from my university that still write grants and edit YALLA\"s literature. I graduated from Baker University in Kansas. I have professors from my university that still write grants and edit YALLA\"s literature. I graduated from Baker University in Kansas. I have professors from my university that still write grants and edit YALLA\"s literature. I graduated from Baker University in Kansas."
    additional_comments                   "N/A"
    three_standout_statistics             "98% of refugee youth in YALLA's 2011 class attended College.\r\n100% of our senior scholar-athletes are enrolled in a college preparatory program. \r\nIn 2012 YALLA served over 600 child survivors of War."
  end
end
