FactoryGirl.define do
  factory :bhsi_application do
    sequence(:id)                        { |n| n }
    first_name                           'John'
    last_name                            'Doe'
    address1                             'Address 1'
    address2                             'Address 2'
    city                                 'Dallas'
    state                                'Texas'
    country                              'USA'
    zipcode                              '11400'
    phone_number                         '123-456-789'
    email                                'john@doe.com'
    gender                               'Male'
    birthdate                            '03/06/1988'
    applied_before                       'No'
    about_yourself                       'I am a serial entrepreneur that loves what I do.'
    title                                'Girls Loving and Respecting Everyone'
    social_venture_name                  'The G.L.A.R.E Club'
    legal_structure                      '501c3'
    url                                  'http://www.url.com'
    twitter_handle                       'twitter'
    video_url                            'N/A'
    social_venture_description           'An organization founded for educational/social purposes.'
    venture_launched                     '05/01/2010'
    number_people_affected               '1700'
    explain_number                       'We have had several successful community outreach events while maintaining our monthly programming.'
    three_standout_statistics            'In December 2011, we gave away 450 toys in the community; In November 2011, we custom made and mailed 1,000 greeting cards to the troops that were in Afghanistan and we continually hold our regular programs which we mentor 45 girls on a monthly basis.'
    organizational_development           'The GLARE Clubs aim is to help better the quality of life in all its realms through community outreach.'
    makes_social_innovation              'What makes The G.L.A.R.E Club a social innovation is that we are here to address the needs of the youth in the community.'
    inspiration                          'My inspiration for starting this organization came from me being a product of a single parent home.'
    sustainability_model                 'We believe that our program will continue to be sustainable over time because we are actively creating strategies that will aid in obtaining the necessary funds to operate consistently.'
    improvements                         'We can improve by expanding our programming to reach more girls in the community.'
    distinguish_yourself                 'The three organizations that we can positively say are the most similar to our organization would be: Saving Our Daughters, Girl Quest and Smart Girl.'
    strong_midwest_connections_explained 'I have a strong connection to the Midwest because I was born and raised in Chicago.'
    additional_comments                  'I would like to thank Chicago Ideas Week and Bluhm/Helfand for this opportunity to present my vision to you.'
    reference_1_name                     'John Doe Jr.'
    reference_1_relationship             'Business Partner'
    reference_1_phone                    '123-456-7890'
    reference_1_email                    'john@doejunior.com'
    reference_2_name                     'N/A'
    reference_2_relationship             'N/A'
    reference_2_phone                    'N/A'
    reference_2_email                    'N/A'
    agreement_accepeted                  true
  end
end
