class RemoveAllForeignKeyConstraints < ActiveRecord::Migration
  def change
    execute "ALTER TABLE affiliate_event_applications DROP FOREIGN KEY affiliate_event_applilcations_user_id_fk;"
    execute "ALTER TABLE chapter_photos DROP FOREIGN KEY chapter_photos_chapter_id_fk;"
    execute "ALTER TABLE chapters DROP FOREIGN KEY chapters_talk_id_fk;"
    execute "ALTER TABLE community_partner_applications DROP FOREIGN KEY community_partner_applications_user_id_fk;"
    execute "ALTER TABLE days DROP FOREIGN KEY days_year_id_fk;"
    execute "ALTER TABLE event_photos DROP FOREIGN KEY event_photos_event_id_fk;"
    execute "ALTER TABLE event_speakers DROP FOREIGN KEY event_speakers_event_id_fk;"
    execute "ALTER TABLE event_speakers DROP FOREIGN KEY event_speakers_speaker_id_fk;"
    execute "ALTER TABLE events DROP FOREIGN KEY events_day_id_fk;"
    execute "ALTER TABLE events DROP FOREIGN KEY events_event_brand_id_fk;"
    execute "ALTER TABLE events DROP FOREIGN KEY events_partner_id_fk;"
    execute "ALTER TABLE events DROP FOREIGN KEY events_venue_id_fk;"
    execute "ALTER TABLE members DROP FOREIGN KEY members_member_type_id_fk;"
    execute "ALTER TABLE members DROP FOREIGN KEY members_user_id_fk;"
    execute "ALTER TABLE members DROP FOREIGN KEY members_year_id_fk;"
    execute "ALTER TABLE notes DROP FOREIGN KEY notes_author_id_fk;"
    execute "ALTER TABLE performances DROP FOREIGN KEY performances_chapter_id_fk;"
    execute "ALTER TABLE performances DROP FOREIGN KEY performances_speaker_id_fk;"
    execute "ALTER TABLE quotes DROP FOREIGN KEY quotes_user_id_fk;"
    execute "ALTER TABLE sponsors DROP FOREIGN KEY sponsors_sponsorship_level_id_fk;"
    execute "ALTER TABLE sponsorships DROP FOREIGN KEY sponsorships_sponsorship_level_id_fk;"
    execute "ALTER TABLE sponsorships DROP FOREIGN KEY sponsorships_sponsor_id_fk;"
    execute "ALTER TABLE sponsorships DROP FOREIGN KEY sponsorships_year_id_fk;"
    execute "ALTER TABLE talk_photos DROP FOREIGN KEY talk_photos_talk_id_fk;"
    execute "ALTER TABLE talks DROP FOREIGN KEY talks_day_id_fk;"
    execute "ALTER TABLE talks DROP FOREIGN KEY talks_sponsor_id_fk;    "
    execute "ALTER TABLE talks DROP FOREIGN KEY talks_talk_brand_id_fk;"
    execute "ALTER TABLE talks DROP FOREIGN KEY talks_track_id_fk;"
    execute "ALTER TABLE talks DROP FOREIGN KEY talks_venue_id_fk;"
    execute "ALTER TABLE volunteers DROP FOREIGN KEY volunteers_user_id_fk;"
  end
end
